project:
  type: website
  output-dir: docs
  resources:
      - "*.xlsx"
      - "*.html"

website:
  title: "Quality Questions"
  sidebar:
    style: docked
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Quality Questions"
        href: quality_questions.qmd
      - text: "Download quality questions HTML template"
        href: quality_questions_html_template.html
      - text: "Download assumptions and decision log Excel template"
        href: "assumptions_and_decision_log_template.xlsx"
      - text: "Assumptions and decision log guide"
        href: assumptions_and_issues_log.qmd
      - text: "Example assumptions log"
        href: sample_assumptions_table.qmd
      - text: "Download commissioning log Excel template"
        href: "commissioning_template.xlsx"
      - text: "FAQs"
        href: faqs.qmd
      - text: "Feedback"
        href: feedback.qmd

format:
  html:
    page-layout: full
    theme: flatly
    toc: true
    embed-resources: true
    
